### ISSUE TITLE
LZ-string compression

### ISSUE THREAD

**Issue by san650** [san650/ember-preferences#31]
Would be great to have the option to use LZ-string compression to store the preferences in local storage when the amount of information is too big.

http://pieroxy.net/blog/pages/lz-string/index.html

It would be great if the dependency that it's included in the end-user project is included in the build only when the LZ compression is enabled.

`preferences.js`

``` js
export default function() {
  compression: 'lz-string'
};
```

**Comment by FLarra** [comment]
PR for this: https://github.com/san650/ember-preferences/pull/37  😃
